version: '3'
services:

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    networks:
      - toto

  redis:
    image: redis:alpine
    container_name: redis
    ports: ["6379"]
    networks:
      - toto

  node1:
    build: ./app
    ports:
      - "8080"
    networks:
      - toto

  node2:
    build: ./app
    ports:
      - "8080"
    networks:
      - toto

networks:
  toto:
